CoreWeatherAPI/Controllers/ForgottenPasswordController.cs
using CoreWeatherAPI.Data;
using CoreWeatherAPI.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CoreWeatherAPI.Controllers
{
    public class ForgottenPasswordController : Controller
    {
        private readonly IUserContextService _userContextService;
        private readonly IForgotPasswordContextService _passwordContextService;

        public ForgottenPasswordController(IUserContextService userContextService,
            IForgotPasswordContextService passwordContextService)
        {
            _userContextService = userContextService;
            _passwordContextService = passwordContextService;
        }

        public IActionResult ForgotPassword()
        {
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> Submit()
        {
            string password = Request.Form["NewPassword"];
            string confirmedPassword = Request.Form["ConfirmPassword"];
            string reqId = Request.Form["ReqId"];

            if (password != confirmedPassword)
                return BadRequest();

            var validRequest = _passwordContextService.GetForgotPasswordRequest(reqId);
            if (validRequest == null)
                return BadRequest();

            var user = _userContextService.GetUserById(validRequest.UserId);
            await _userContextService.ResetPassword(confirmedPassword, user.Id);
            validRequest.IsFulfilled = true;
            var result = await _passwordContextService.UpdateRequest(validRequest);
            return Ok(result);
        }
    }
}

CoreWeatherAPI/Views/ForgottenPassword/ForgotPassword.cshtml
@page "{id}"
@{
    var req = ViewContext.RouteData.Values["id"];
}
<style type="text/css">
    #wrapper {
        width: 760px;
        margin: auto
    }

</style>

<h2 id="wrapper">Forgot Password</h2>

@using (Html.BeginForm("Submit", "ForgottenPassword", FormMethod.Post))
{
    <div id="wrapper" class="form-horizontal">
        <hr />
        <div class="form-group">
            <label class="control-label col-md-2">New Password</label>
            @Html.TextBox("NewPassword", "", new { @class = "form--control" })
        </div>
        <div class="form-group">
            <label class="control-label col-md-2">Confirm Password</label>
            @Html.TextBox("ConfirmPassword", "", new { @class = "form--control" })
        </div>
        <div class="form-group">
            @Html.Hidden("ReqId", req)
            <input type="submit" value="Reset Password" class="btn btn-success" />
        </div>
    </div>
}